# Generated by Django 3.2.6 on 2021-08-30 01:12

from django.db import migrations
from ..models import \
    NodeTypes,\
    Nodes,\
    Tables,\
    Columns


def create_node_types(apps, schema_editor):
    node_type_1 = NodeTypes()
    node_type_1.node_type_name = 'instance1'
    node_type_1.save()

    node_type_2 = NodeTypes()
    node_type_2.node_type_name = 'instance2'
    node_type_2.save()


def create_nodes(apps, schema_editor):
    node_1 = Nodes()
    node_1.node_name = 'CONSUMPTION'
    node_1.node_type_id = 1
    node_1.save()

    node_2 = Nodes()
    node_2.node_name = 'ORACLE'
    node_2.node_type_id = 1
    node_2.save()

    node_3 = Nodes()
    node_3.node_name = 'ORCL'
    node_3.node_type_id = 1
    node_3.save()

    node_4 = Nodes()
    node_4.node_name = 'REFINED'
    node_4.node_type_id = 1
    node_4.save()

    node_5 = Nodes()
    node_5.node_name = 'SNOWFLAKE'
    node_5.node_type_id = 1
    node_5.save()


def create_tables(apps, schema_editor):
    table_1 = Tables()
    table_1.table_name = 'CUSTOMERSALESINSIGHTS'
    table_1.description = 'Customer Sales Insights Table'
    table_1.node_id = 5
    table_1.save()

    table_2 = Tables()
    table_2.table_name = 'PRODUCTSALESINSIGHTS'
    table_2.description = 'Product Sales Insights Table'
    table_2.node_id = 5
    table_2.save()


def create_columns(apps, schema_editor):
    column_1 = Columns()
    column_1.column_name = 'EMAILADDRESS'
    column_1.description = 'Email Address'
    column_1.table_id = 1
    column_1.save()

    column_2 = Columns()
    column_2.column_name = 'SALESORDERNUMBER'
    column_2.description = 'Sales Order Number'
    column_2.table_id = 1
    column_2.save()

    column_3 = Columns()
    column_3.column_name = 'ORDERQUANTITY'
    column_3.description = 'Order Quantity'
    column_3.table_id = 1
    column_3.save()

    column_4 = Columns()
    column_4.column_name = 'FULLNAME'
    column_4.description = 'Full Name'
    column_4.table_id = 1
    column_4.save()

    column_5 = Columns()
    column_5.column_name = 'CUSTOMERKEY'
    column_5.description = 'Customer Key'
    column_5.table_id = 1
    column_5.save()

    column_6 = Columns()
    column_6.column_name = 'SALESAMOUNT'
    column_6.description = 'Sales Amount'
    column_6.table_id = 1
    column_6.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_node_types),
        migrations.RunPython(create_nodes),
        migrations.RunPython(create_tables),
        migrations.RunPython(create_columns),
    ]
